### ISSUE TITLE
加油实现右上角自定义按钮哦

### ISSUE THREAD

**Issue by hyacinthus** [moyuanhua/taro-navbar#1]
官方那个适配方面太鸡肋了

**Comment by moyuanhua** [comment]
> 官方那个适配方面太鸡肋了

我也觉得  不过 兄台 右上角已经有胶囊了啊   如果有需要的话可以直接改源码哦 很简单的结构
https://github.com/moyuanhua/taro-navbar/tree/master/src/components/navbar
